/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dadoclimatico.dadoclimatico.view;

import com.mycompany.dadoclimatico.dadoclimatico.model.DadoClima;
import com.mycompany.dadoclimatico.dadoclimatico.utils.DataUtil;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mario e Álvaro
 */
public class ClimaFrame extends javax.swing.JFrame {

    private DadoClima dado = new DadoClima();

    /**
     * Creates new form ClimaFrame
     */
    public ClimaFrame() {
        initComponents();
        this.setVisible(true);
        this.frmConfiguracao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        frmDadosInclude = new javax.swing.JInternalFrame();
        lblData = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInclude_Data = new javax.swing.JTextField();
        txtInclude_Temperatura = new javax.swing.JTextField();
        txtInclude_Umidade = new javax.swing.JTextField();
        txtInclude_Pressão = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        frmDadosMedios = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMedia_Temperatura = new javax.swing.JLabel();
        lblMedia_Umidade = new javax.swing.JLabel();
        lblMedia_Pressao = new javax.swing.JLabel();
        lblMedia_nrRegistros = new javax.swing.JLabel();
        frmUltimaAtt = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUltimo_Temperatura = new javax.swing.JLabel();
        lblUltimo_Umidade = new javax.swing.JLabel();
        lblUltimo_Pressao = new javax.swing.JLabel();
        lblUltimo_Data = new javax.swing.JLabel();
        frmRegistros = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        frmGrafico = new javax.swing.JInternalFrame();
        lblNumeroRegistros_Painel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        frmConfiguracao = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frmDadosInclude.setResizable(true);
        frmDadosInclude.setTitle("Dados do Tempo");
        frmDadosInclude.setPreferredSize(new java.awt.Dimension(300, 180));
        frmDadosInclude.setVisible(true);

        lblData.setText("Data:");

        lblTemperatura.setText("Temperatura:");

        jLabel3.setText("Umidade:");

        jLabel4.setText("Pressão:");

        txtInclude_Data.setText("DD/MM/AAAA");

        txtInclude_Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInclude_TemperaturaActionPerformed(evt);
            }
        });

        txtInclude_Umidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInclude_UmidadeActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncluirMouseClicked(evt);
            }
        });
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmDadosIncludeLayout = new javax.swing.GroupLayout(frmDadosInclude.getContentPane());
        frmDadosInclude.getContentPane().setLayout(frmDadosIncludeLayout);
        frmDadosIncludeLayout.setHorizontalGroup(
            frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmDadosIncludeLayout.createSequentialGroup()
                .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frmDadosIncludeLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblTemperatura)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInclude_Data)
                            .addComponent(txtInclude_Temperatura)
                            .addComponent(txtInclude_Umidade)
                            .addComponent(txtInclude_Pressão, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frmDadosIncludeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIncluir)))
                .addGap(18, 18, 18))
        );
        frmDadosIncludeLayout.setVerticalGroup(
            frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDadosIncludeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtInclude_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura)
                    .addComponent(txtInclude_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInclude_Umidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmDadosIncludeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtInclude_Pressão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIncluir)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        frmDadosMedios.setTitle("Dados Médios");
        frmDadosMedios.setPreferredSize(new java.awt.Dimension(300, 190));
        frmDadosMedios.setVisible(true);

        jLabel1.setText("Temperatura Média:");

        jLabel2.setText("Umidade Média:");

        jLabel5.setText("Pressão Média:");

        jLabel6.setText("Número de Registros:");

        lblMedia_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedia_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedia_Temperatura.setText("jLabel7");
        lblMedia_Temperatura.setToolTipText("");

        lblMedia_Umidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedia_Umidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedia_Umidade.setText("jLabel9");
        lblMedia_Umidade.setToolTipText("");

        lblMedia_Pressao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedia_Pressao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedia_Pressao.setText("jLabel10");
        lblMedia_Pressao.setToolTipText("");

        lblMedia_nrRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedia_nrRegistros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedia_nrRegistros.setText("jLabel11");
        lblMedia_nrRegistros.setToolTipText("");

        javax.swing.GroupLayout frmDadosMediosLayout = new javax.swing.GroupLayout(frmDadosMedios.getContentPane());
        frmDadosMedios.getContentPane().setLayout(frmDadosMediosLayout);
        frmDadosMediosLayout.setHorizontalGroup(
            frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDadosMediosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMedia_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMedia_Umidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMedia_Pressao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedia_nrRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        frmDadosMediosLayout.setVerticalGroup(
            frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmDadosMediosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMedia_Temperatura))
                .addGap(16, 16, 16)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMedia_Umidade))
                .addGap(16, 16, 16)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMedia_Pressao))
                .addGap(16, 16, 16)
                .addGroup(frmDadosMediosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblMedia_nrRegistros))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        frmUltimaAtt.setResizable(true);
        frmUltimaAtt.setTitle("Última Atualização do Tempo");
        frmUltimaAtt.setVisible(true);

        jLabel7.setText("Temperatura:");

        jLabel9.setText("Umidade:");

        jLabel10.setText("Pressão:");

        jLabel11.setText("Data:");

        lblUltimo_Temperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUltimo_Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUltimo_Temperatura.setText("jLabel12");

        lblUltimo_Umidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUltimo_Umidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUltimo_Umidade.setText("jLabel13");

        lblUltimo_Pressao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUltimo_Pressao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUltimo_Pressao.setText("jLabel14");

        lblUltimo_Data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUltimo_Data.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUltimo_Data.setText("jLabel15");
        lblUltimo_Data.setMaximumSize(new java.awt.Dimension(140, 16));

        javax.swing.GroupLayout frmUltimaAttLayout = new javax.swing.GroupLayout(frmUltimaAtt.getContentPane());
        frmUltimaAtt.getContentPane().setLayout(frmUltimaAttLayout);
        frmUltimaAttLayout.setHorizontalGroup(
            frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmUltimaAttLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmUltimaAttLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUltimo_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmUltimaAttLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUltimo_Pressao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmUltimaAttLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUltimo_Umidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmUltimaAttLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(lblUltimo_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        frmUltimaAttLayout.setVerticalGroup(
            frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmUltimaAttLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblUltimo_Temperatura))
                .addGap(17, 17, 17)
                .addGroup(frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblUltimo_Umidade))
                .addGap(17, 17, 17)
                .addGroup(frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblUltimo_Pressao))
                .addGap(17, 17, 17)
                .addGroup(frmUltimaAttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblUltimo_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        frmRegistros.setTitle("Registros");
        frmRegistros.setVisible(true);

        tblRegistros.setAutoCreateRowSorter(true);
        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Temperatura", "Umidade", "Pressão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRegistros);
        if (tblRegistros.getColumnModel().getColumnCount() > 0) {
            tblRegistros.getColumnModel().getColumn(0).setHeaderValue("Data");
            tblRegistros.getColumnModel().getColumn(1).setHeaderValue("Temperatura");
            tblRegistros.getColumnModel().getColumn(2).setHeaderValue("Umidade");
            tblRegistros.getColumnModel().getColumn(3).setHeaderValue("Pressão");
        }

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmRegistrosLayout = new javax.swing.GroupLayout(frmRegistros.getContentPane());
        frmRegistros.getContentPane().setLayout(frmRegistrosLayout);
        frmRegistrosLayout.setHorizontalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmRegistrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemove)))
                .addContainerGap())
        );
        frmRegistrosLayout.setVerticalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addContainerGap())
        );

        frmGrafico.setTitle("Máximas e Mínimas");
        frmGrafico.setVisible(true);

        javax.swing.GroupLayout frmGraficoLayout = new javax.swing.GroupLayout(frmGrafico.getContentPane());
        frmGrafico.getContentPane().setLayout(frmGraficoLayout);
        frmGraficoLayout.setHorizontalGroup(
            frmGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmGraficoLayout.setVerticalGroup(
            frmGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblNumeroRegistros_Painel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroRegistros_Painel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumeroRegistros_Painel.setText("Número de Registros: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmConfiguracao.setTitle("Configuração do Sistema");
        frmConfiguracao.setVisible(true);

        jLabel12.setText("Log:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JSON", "XML" }));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmConfiguracaoLayout = new javax.swing.GroupLayout(frmConfiguracao.getContentPane());
        frmConfiguracao.getContentPane().setLayout(frmConfiguracaoLayout);
        frmConfiguracaoLayout.setHorizontalGroup(
            frmConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmConfiguracaoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(frmConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(frmConfiguracaoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        frmConfiguracaoLayout.setVerticalGroup(
            frmConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmConfiguracaoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(frmConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jMenu1.setText("Configurar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumeroRegistros_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(frmDadosInclude, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmGrafico))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(frmConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(frmDadosMedios, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                                    .addComponent(frmUltimaAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frmRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frmRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(9, Short.MAX_VALUE)
                                .addComponent(frmUltimaAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(frmConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(frmDadosMedios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frmDadosInclude, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(frmGrafico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNumeroRegistros_Painel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInclude_TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInclude_TemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInclude_TemperaturaActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        if(frmConfiguracao.isVisible())
            frmConfiguracao.setVisible(false);
        else
            frmConfiguracao.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncluirMouseClicked

    private void txtInclude_UmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInclude_UmidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInclude_UmidadeActionPerformed

    
    public JButton getBtnIncluir(){
        return this.btnIncluir;
    }

    public JButton getBtnRemove() {
        return btnRemove;
    }

    public void setBtnRemove(JButton btnRemove) {
        this.btnRemove = btnRemove;
    }

    public JLabel getLblData() {
        return lblData;
    }

    public void setLblData(JLabel lblData) {
        this.lblData = lblData;
    }

    public JLabel getLblMedia_Pressao() {
        return lblMedia_Pressao;
    }

    public void setLblMedia_Pressao(JLabel lblMedia_Pressao) {
        this.lblMedia_Pressao = lblMedia_Pressao;
    }

    public JLabel getLblMedia_Temperatura() {
        return lblMedia_Temperatura;
    }

    public void setLblMedia_Temperatura(JLabel lblMedia_Temperatura) {
        this.lblMedia_Temperatura = lblMedia_Temperatura;
    }

    public JLabel getLblMedia_Umidade() {
        return lblMedia_Umidade;
    }

    public void setLblMedia_Umidade(JLabel lblMedia_Umidade) {
        this.lblMedia_Umidade = lblMedia_Umidade;
    }

    public JLabel getLblMedia_nrRegistros() {
        return lblMedia_nrRegistros;
    }

    public void setLblMedia_nrRegistros(JLabel lblMedia_nrRegistros) {
        this.lblMedia_nrRegistros = lblMedia_nrRegistros;
    }

    public JLabel getLblNumeroRegistros_Painel() {
        return lblNumeroRegistros_Painel;
    }

    public void setLblNumeroRegistros_Painel(JLabel lblNumeroRegistros_Painel) {
        this.lblNumeroRegistros_Painel = lblNumeroRegistros_Painel;
    }

    public JLabel getLblTemperatura() {
        return lblTemperatura;
    }

    public void setLblTemperatura(JLabel lblTemperatura) {
        this.lblTemperatura = lblTemperatura;
    }

    public JLabel getLblUltimo_Data() {
        return lblUltimo_Data;
    }

    public void setLblUltimo_Data(JLabel lblUltimo_Data) {
        this.lblUltimo_Data = lblUltimo_Data;
    }

    public JLabel getLblUltimo_Pressao() {
        return lblUltimo_Pressao;
    }

    public void setLblUltimo_Pressao(JLabel lblUltimo_Pressao) {
        this.lblUltimo_Pressao = lblUltimo_Pressao;
    }

    public JLabel getLblUltimo_Temperatura() {
        return lblUltimo_Temperatura;
    }

    public void setLblUltimo_Temperatura(JLabel lblUltimo_Temperatura) {
        this.lblUltimo_Temperatura = lblUltimo_Temperatura;
    }

    public JLabel getLblUltimo_Umidade() {
        return lblUltimo_Umidade;
    }

    public void setLblUltimo_Umidade(JLabel lblUltimo_Umidade) {
        this.lblUltimo_Umidade = lblUltimo_Umidade;
    }

    public JTable getTblRegistros() {
        return tblRegistros;
    }

    public void setTblRegistros(JTable tblRegistros) {
        this.tblRegistros = tblRegistros;
    }

    public JTextField getTxtInclude_Data() {
        dado.setData( DataUtil.stringToData(txtInclude_Data.getText()));
        return txtInclude_Data;
    }

    public void setTxtInclude_Data(JTextField txtInclude_Data) {
        this.txtInclude_Data = txtInclude_Data;
    }

    public JTextField getTxtInclude_Pressao() {
        dado.setPressao(Float.parseFloat(txtInclude_Pressão.getText()));
        return txtInclude_Pressão;
    }

    public void setTxtInclude_Pressao(JTextField txtInclude_Pressão) {
        this.txtInclude_Pressão = txtInclude_Pressão;
    }

    public JTextField getTxtInclude_Temperatura() {
        dado.setTemperatura(Float.parseFloat(txtInclude_Temperatura.getText()));
        return txtInclude_Temperatura;
    }

    public void setTxtInclude_Temperatura(JTextField txtInclude_Temperatura) {
        this.txtInclude_Temperatura = txtInclude_Temperatura;
    }

    public JTextField getTxtInclude_Umidade() {
        dado.setUmidade(Float.parseFloat(txtInclude_Umidade.getText()));
        return txtInclude_Umidade;
    }

    public void setTxtInclude_Umidade(JTextField txtInclude_Umidade) {
        this.txtInclude_Umidade = txtInclude_Umidade;
    }
    
    public DadoClima getDado(){
        return dado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRemove;
    private javax.swing.JInternalFrame frmConfiguracao;
    private javax.swing.JInternalFrame frmDadosInclude;
    private javax.swing.JInternalFrame frmDadosMedios;
    private javax.swing.JInternalFrame frmGrafico;
    private javax.swing.JInternalFrame frmRegistros;
    private javax.swing.JInternalFrame frmUltimaAtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMedia_Pressao;
    private javax.swing.JLabel lblMedia_Temperatura;
    private javax.swing.JLabel lblMedia_Umidade;
    private javax.swing.JLabel lblMedia_nrRegistros;
    private javax.swing.JLabel lblNumeroRegistros_Painel;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblUltimo_Data;
    private javax.swing.JLabel lblUltimo_Pressao;
    private javax.swing.JLabel lblUltimo_Temperatura;
    private javax.swing.JLabel lblUltimo_Umidade;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtInclude_Data;
    private javax.swing.JTextField txtInclude_Pressão;
    private javax.swing.JTextField txtInclude_Temperatura;
    private javax.swing.JTextField txtInclude_Umidade;
    // End of variables declaration//GEN-END:variables
}
